### PR TITLE
Added process of booleans

### PR DESCRIPTION
**Pull request by jaumarar**
If the .env file has a boolean value it will be parsed into the correct type:

.env file:
`VARIABLE=true`

Before:
`$_ENV['VARIABLE] = 'true';`

Now:
`$_ENV['VARIABLE] = true;`

- Also added test and make this option configurable via `DotEnv::PROCESS_BOOLEANS`. 
- Attribute `@runInSeparateProcess` has been added to the test to restart `$_ENV` variables

### CODE REVIEW

**Review by michelphp — CHANGES_REQUESTED** [review]
I approve the changes but I have a few remarks:

- In processValue  declare argument type as string
- In load function , is not necessary return the values that have been loaded into ENV

Thanks

**Comment by jaumarar** [comment]
Perfect, I think all changes have been made

**Comment by michelphp** [comment]
Ok for me , thanks

**Comment by michelphp** [comment]
You are forget to remove unit test about returns values : 

  /**
     * @runInSeparateProcess
     */
    public function testLoadReturnsValues()
    {
        $loaded = (new DotEnv($this->env('.env.return')))->load();

        $this->assertEquals('returned', $loaded['VALUE']);
        $this->assertEquals('returned', $_ENV['VALUE']);
    }

test failed

**Pull request merged**
